require:
  - rubocop-airbnb
  - rubocop-performance
  - rubocop-graphql
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - ".rvm/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
