inherit_from:
  - config/rubocop/default.yml
  - .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.3
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - ".rvm/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "public/**/*"
    - "db/schema.rb"
