require:
  - rubocop-performance
inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.7.3
Security:
  Enabled: true
Rails/OutputSafety:
  Enabled: true
Style/MutableConstant:
  Enabled: true
