require:
  - rubocop-airbnb
  - rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - ".rvm/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "public/**/*"
    - "db/schema.rb"
