inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/default.yml
require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.6
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - ".rvm/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "public/**/*"
    - "db/schema.rb"
Layout/LineLength:
  Max: 130
  AllowURI: true
