name: Heroku Staging Deployment
on:
  push:
    branches: []
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: openmanifest
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false
